### ISSUE TITLE
This app isn't verified

### ISSUE THREAD

**Issue by JaniniRami** [vtorres/youcheater#2]
When running the script and going to the verification link is shows an error "This app isn't verified" on the webpage any idea of how to fix it?

**Comment by vtorres** [comment]
Hey @JaniniRami07 
_**Short answer**_: You can still use it. On the "This app isn't verified" screen there is an "Advanced" link which you can continue to the next steps
_**Long answer**_: A new process came recently to protect user's data showing the "unverified app" screen when the OAuth request includes a sensible scope, scope which makes possible the integration. So, if your generated API is not published and not verified you can start the google verification by submitting [here](https://support.google.com/code/contact/oauth_app_verification) the scopes justification, BUT you don't need to bother if only you gonna use it, only in the case of you distribute it as a product on the future!

**Comment by vtorres** [comment]
Hey @JaniniRami07 
Short answer: You can still use it. On the "This app isn't verified" screen there is an "Advanced" link which you can continue to the next steps
Long answer: A new process came recently to protect user's data showing the "unverified app" screen when the OAuth request includes a sensible scope, scope which makes possible the integration. So, if your generated API is not published and not verified you can start the google verification by submitting here the scopes justification, BUT you don't need to bother if only you gonna use it, only in the case of you distribute it as a product on the future

**Comment by vtorres** [comment]
Hey @JaniniRami07 
_**Short answer**_: You can still use it. On the "This app isn't verified" screen there is an "Advanced" link which you can continue to the next steps
_**Long answer**_: A new process came recently to protect user's data showing the "unverified app" screen when the OAuth request includes a sensible scope, scope which makes possible the integration. So, if your generated API is not published and not verified you can start the google verification by submitting [here](https://support.google.com/code/contact/oauth_app_verification) the scopes justification, BUT you don't need to bother if only you gonna use it, only in the case of you distribute it as a product on the future
